<?php

namespace PN\Bundle\ProductBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use PN\Bundle\ProductBundle\Entity\Collection;
use PN\Utils\Validate;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository {

    public function getCategoryOptions() {
        $mainCategory = $this->findBy(['parent' => NULL, 'deleted' => NULL]);

        $list = array();
        foreach ($mainCategory as $cat) {
            $list[$cat->getTitle()] = [];

            foreach ($cat->getChildren() as $sub) {
                $list[$cat->getTitle()][$sub->getId()] = $sub;
            }
        }
        return $list;
    }

    public function getCategoriesByCollection(Collection $collection){
        $statement=$this->createQueryBuilder('c')
            ->leftJoin("c.products", 'p')
            ->leftJoin("p.collections", 'col')
            ->where("col.id = :collectionId")
            ->andWhere("p.publish= true")
            ->andWhere("c.deleted IS NULL")
            ->andWhere("p.deleted IS NULL")
            ->setParameter("collectionId", $collection->getId())
            ->groupBy("c.id")
        ;
        return $statement->getQuery()->execute();
    }

    private function getStatement() {
        return $this->createQueryBuilder('c')
            ->leftJoin("c.products", 'p');
    }

    private function filterOrder(QueryBuilder $statement, \stdClass $search) {
        $sortSQL = [
            'c.id',
            'c.tarteb',
            'c.title',
            'c.noOfProducts',
            'c.noOfPublishProducts',
            'c.created'
        ];

        if (isset($search->ordr) and Validate::not_null($search->ordr)) {
            $dir = $search->ordr['dir'];
            $columnNumber = $search->ordr['column'];
            if (isset($columnNumber) and array_key_exists($columnNumber, $sortSQL)) {
                $statement->addOrderBy($sortSQL[$columnNumber], $dir);
            }
        } else {
            $statement->addOrderBy($sortSQL[1]);
        }
    }


    private function filterWhereClause(QueryBuilder $statement, \stdClass $search) {
        if (isset($search->string) and Validate::not_null($search->string)) {
            $statement->andWhere('c.id LIKE :searchTerm '
                . 'OR c.title LIKE :searchTerm '
            );
            $statement->setParameter('searchTerm', '%' . trim($search->string) . '%');
        }

        if (isset($search->parent) and $search->parent != "") {
            $statement->andWhere('c.parent = :parent');
            $statement->setParameter('parent', $search->parent);
        } elseif (isset($search->parent) and $search->parent == "") {
            $statement->andWhere('c.parent IS NULL');
        }

        if (isset($search->hasProducts) and $search->hasProducts == true) {
            $statement->andHaving('noOfProducts > 0');
        }

        if(isset($search->ids) and is_array($search->ids)) {
            $statement->andWhere("c.id IN (:ids)");
            $statement->setParameter('ids' , $search->ids);
        }

        if (isset($search->deleted) and in_array($search->deleted, array(0, 1))) {
            if ($search->deleted == 1) {
                $statement->andWhere('c.deleted IS NOT NULL');
            } else {
                $statement->andWhere('c.deleted IS NULL');
            }
        }
    }

    private function filterPagination(QueryBuilder $statement, $startLimit = NULL, $endLimit = NULL) {
        if ($startLimit === NULL or $endLimit === NULL) {
            return false;
        }
        $statement->setFirstResult($startLimit)
            ->setMaxResults($endLimit);
    }

    private function filterCount(QueryBuilder $statement) {
        $statement->select("COUNT(DISTINCT c.id)");
        $statement->setMaxResults(1);

        $count = $statement->getQuery()->getOneOrNullResult();
        if (is_array($count) and count($count) > 0) {
            return (int)reset($count);
        }
        return 0;
    }

    public function filter($search, $count = FALSE, $startLimit = NULL, $endLimit = NULL) {
        $statement = $this->getStatement();
        $this->filterWhereClause($statement, $search);

        if ($count == true) {
            return $this->filterCount($statement);
        }

        $statement->groupBy('c.id');
        $this->filterPagination($statement, $startLimit, $endLimit);
        $this->filterOrder($statement, $search);
        return  $statement->getQuery()->execute();
    }


}
