<?php

namespace PN\Bundle\ProductBundle\Repository;

use PN\Bundle\ProductBundle\Entity\SearchKeyword;
use PN\Utils\IPService;

/**
 * UnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchKeywordsRepository extends \Doctrine\ORM\EntityRepository {

    private function canonicalizeKeyword($keyword) {
        $keyword = trim($keyword);
        $keyword = strtolower($keyword);
        $keyword = preg_replace('/\s+/', '-', $keyword);
        return strtolower($keyword);
    }

    public function insert($keyword) {
        $keyword = trim($keyword);
        $canonicalKeyword = $this->canonicalizeKeyword($keyword);
        $ip = IPService::getIp();
        $searchKeyword = $this->findOneBy(['canonicalKeyword' => $canonicalKeyword, "ip" => $ip]);
        if (!$searchKeyword) {
            $searchKeyword = new SearchKeyword();
            $searchKeyword->setKeyword($keyword);
            $searchKeyword->setCanonicalKeyword($canonicalKeyword);
            $searchKeyword->setIp($ip);
        }

        $em = $this->getEntityManager();
        $em->persist($searchKeyword);
        $em->flush();
    }

    public function topSearchKeywords($limit = 10) {
        $statement = $this->createQueryBuilder("s")
            ->select("s.keyword, COUNT(s.canonicalKeyword) countKeywords")
            ->orderBy("countKeywords", "DESC")
            ->groupBy("s.canonicalKeyword")
            ->setMaxResults($limit);
        return $statement->getQuery()->getResult();
    }
}
