# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER,ROLE_SEO,ROLE_IMAGE_GALLERY
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_provider:
            chain:
                providers: [in_memory, fos_userbundle]
        in_memory:
            memory:
                users:
                    super@admin.pn: { password: 0f77d4f39eb84f9e5724a759767690971354b73d , roles: [ 'ROLE_SUPER_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            form_login:
                provider: user_provider
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                default_target_path: dashboard

            logout_on_user_change: TRUE
            logout: 
                path:           /logout
                target:         fos_user_security_login
            anonymous:    true
                   

    access_control:
          - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/, role: [ROLE_ADMIN,ROLE_IMAGE_GALLERY] }
#          - { path: ^/api/secure/, role: ROLE_USER }
