<?php declare(strict_types=1);

namespace Application\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210929140546 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {

        $this->addSql('CREATE TABLE ext_log_entries (id INT AUTO_INCREMENT NOT NULL, action VARCHAR(8) NOT NULL, logged_at DATETIME NOT NULL, object_id VARCHAR(64) DEFAULT NULL, object_class VARCHAR(255) NOT NULL, version INT NOT NULL, data LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', username VARCHAR(255) DEFAULT NULL, INDEX log_class_lookup_idx (object_class), INDEX log_date_lookup_idx (logged_at), INDEX log_user_lookup_idx (username), INDEX log_version_lookup_idx (object_id, object_class, version), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB ROW_FORMAT = DYNAMIC');
        $this->addSql('CREATE TABLE seo_social_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, image_url VARCHAR(255) DEFAULT NULL, INDEX IDX_4DC1EE9B2C2AC5D3 (translatable_id), INDEX IDX_4DC1EE9B82F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seo_base_route (id INT AUTO_INCREMENT NOT NULL, entity_name VARCHAR(255) NOT NULL, base_route VARCHAR(255) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, UNIQUE INDEX UNIQ_B98C855216EFC72D (entity_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seo_page (id INT AUTO_INCREMENT NOT NULL, seo_id INT DEFAULT NULL, title VARCHAR(100) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, UNIQUE INDEX UNIQ_E8DCA6F197E3DD86 (seo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seo_social (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, image_url VARCHAR(255) DEFAULT NULL, social_network SMALLINT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE redirect_404 (id INT AUTO_INCREMENT NOT NULL, `from` LONGTEXT NOT NULL, `to` LONGTEXT NOT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE language (id INT AUTO_INCREMENT NOT NULL, locale VARCHAR(5) NOT NULL, title VARCHAR(45) NOT NULL, flag_asset VARCHAR(45) NOT NULL, UNIQUE INDEX UNIQ_D4DB71B54180C698 (locale), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image_setting (id INT AUTO_INCREMENT NOT NULL, entity_name VARCHAR(255) DEFAULT NULL, back_route VARCHAR(255) DEFAULT NULL, upload_path VARCHAR(255) DEFAULT NULL, auto_resize TINYINT(1) NOT NULL, quality SMALLINT NOT NULL, gallery TINYINT(1) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, UNIQUE INDEX UNIQ_A64EF4416EFC72D (entity_name), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image_type (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image_setting_has_type (image_type_id INT NOT NULL, image_setting_id INT NOT NULL, radio_button TINYINT(1) NOT NULL, width DOUBLE PRECISION DEFAULT NULL, height DOUBLE PRECISION DEFAULT NULL, thumb_width DOUBLE PRECISION DEFAULT NULL, thumb_height DOUBLE PRECISION DEFAULT NULL, validate_width_and_height TINYINT(1) NOT NULL, validate_size TINYINT(1) NOT NULL, INDEX IDX_F8AEE740505CDB4F (image_type_id), INDEX IDX_F8AEE74082EBAA44 (image_setting_id), PRIMARY KEY(image_type_id, image_setting_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dynamic_content_attribute_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, value LONGTEXT DEFAULT NULL, INDEX IDX_A4504A102C2AC5D3 (translatable_id), INDEX IDX_A4504A1082F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dynamic_content (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(50) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dynamic_content_attribute (id INT AUTO_INCREMENT NOT NULL, dynamic_content_id INT DEFAULT NULL, title VARCHAR(50) NOT NULL, value LONGTEXT DEFAULT NULL, type SMALLINT NOT NULL, hint VARCHAR(255) DEFAULT NULL, image_width DOUBLE PRECISION DEFAULT NULL, image_height DOUBLE PRECISION DEFAULT NULL, INDEX IDX_E7247B59D9D0CD7 (dynamic_content_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dynamic_content_attribute_image (dynamic_content_attribute_id INT NOT NULL, image_id INT NOT NULL, INDEX IDX_697B9E6EF5E49404 (dynamic_content_attribute_id), INDEX IDX_697B9E6E3DA5256D (image_id), PRIMARY KEY(dynamic_content_attribute_id, image_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dynamic_content_attribute_document (dynamic_content_attribute_id INT NOT NULL, document_id INT NOT NULL, INDEX IDX_E9D18348F5E49404 (dynamic_content_attribute_id), INDEX IDX_E9D18348C33F7837 (document_id), PRIMARY KEY(dynamic_content_attribute_id, document_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, content LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', INDEX IDX_6D8AA7542C2AC5D3 (translatable_id), INDEX IDX_6D8AA75482F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post (id INT AUTO_INCREMENT NOT NULL, content LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE post_image (post_id INT NOT NULL, image_id INT NOT NULL, INDEX IDX_522688B04B89032C (post_id), INDEX IDX_522688B03DA5256D (image_id), PRIMARY KEY(post_id, image_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project (id INT AUTO_INCREMENT NOT NULL, post_id INT DEFAULT NULL, seo_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, interior_designer_name VARCHAR(255) DEFAULT NULL, client VARCHAR(120) DEFAULT NULL, date DATETIME DEFAULT NULL, project_scope VARCHAR(255) DEFAULT NULL, tarteb SMALLINT DEFAULT NULL, featured TINYINT(1) NOT NULL, publish TINYINT(1) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(30) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, UNIQUE INDEX UNIQ_2FB3D0EE4B89032C (post_id), UNIQUE INDEX UNIQ_2FB3D0EE97E3DD86 (seo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE projects_services (project_id INT NOT NULL, service_id INT NOT NULL, INDEX IDX_19AF0280166D1F9C (project_id), INDEX IDX_19AF0280ED5CA9E6 (service_id), PRIMARY KEY(project_id, service_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dynamic_page (id INT AUTO_INCREMENT NOT NULL, seo_id INT DEFAULT NULL, post_id INT DEFAULT NULL, title VARCHAR(50) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, UNIQUE INDEX UNIQ_575ACC497E3DD86 (seo_id), UNIQUE INDEX UNIQ_575ACC44B89032C (post_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE team (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, name VARCHAR(100) NOT NULL, position VARCHAR(50) NOT NULL, tarteb SMALLINT DEFAULT NULL, short_desc LONGTEXT NOT NULL, publish TINYINT(1) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(30) DEFAULT NULL, UNIQUE INDEX UNIQ_C4E0A61F3DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE partner (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, title VARCHAR(50) NOT NULL, url VARCHAR(255) DEFAULT NULL, tarteb SMALLINT DEFAULT NULL, rating INT DEFAULT NULL, review LONGTEXT DEFAULT NULL, publish TINYINT(1) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(30) DEFAULT NULL, UNIQUE INDEX UNIQ_312B3E163DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE faq (id INT AUTO_INCREMENT NOT NULL, question LONGTEXT NOT NULL, answer LONGTEXT NOT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) NOT NULL, INDEX IDX_191BAF622C2AC5D3 (translatable_id), INDEX IDX_191BAF6282F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE project_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) NOT NULL, interior_designer_name VARCHAR(255) DEFAULT NULL, client VARCHAR(120) DEFAULT NULL, project_scope VARCHAR(255) DEFAULT NULL, INDEX IDX_EC103EE42C2AC5D3 (translatable_id), INDEX IDX_EC103EE482F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE faq_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, question LONGTEXT NOT NULL, answer LONGTEXT NOT NULL, INDEX IDX_99569DA22C2AC5D3 (translatable_id), INDEX IDX_99569DA282F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE dynamic_page_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) NOT NULL, INDEX IDX_5512AA682C2AC5D3 (translatable_id), INDEX IDX_5512AA6882F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE team_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, name VARCHAR(100) NOT NULL, position VARCHAR(50) NOT NULL, short_desc LONGTEXT NOT NULL, INDEX IDX_CE31D7452C2AC5D3 (translatable_id), INDEX IDX_CE31D74582F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blogger_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) NOT NULL, INDEX IDX_E01D7E42C2AC5D3 (translatable_id), INDEX IDX_E01D7E482F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE partner_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(50) NOT NULL, review LONGTEXT DEFAULT NULL, INDEX IDX_579AC5A62C2AC5D3 (translatable_id), INDEX IDX_579AC5A682F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE banner_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(50) NOT NULL, sub_title VARCHAR(35) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, text VARCHAR(255) DEFAULT NULL, INDEX IDX_F8B8D8B2C2AC5D3 (translatable_id), INDEX IDX_F8B8D8B82F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE banner (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, title VARCHAR(50) NOT NULL, sub_title VARCHAR(35) DEFAULT NULL, placement INT NOT NULL, url VARCHAR(255) DEFAULT NULL, text VARCHAR(255) DEFAULT NULL, openType TINYINT(1) NOT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, UNIQUE INDEX UNIQ_6F9DB8E73DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE service (id INT AUTO_INCREMENT NOT NULL, post_id INT DEFAULT NULL, seo_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, publish TINYINT(1) NOT NULL, tarteb INT NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(30) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, UNIQUE INDEX UNIQ_E19D9AD24B89032C (post_id), UNIQUE INDEX UNIQ_E19D9AD297E3DD86 (seo_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blogger (id INT AUTO_INCREMENT NOT NULL, seo_id INT DEFAULT NULL, post_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, publish TINYINT(1) NOT NULL, date DATETIME DEFAULT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(30) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, UNIQUE INDEX UNIQ_A8F930E297E3DD86 (seo_id), UNIQUE INDEX UNIQ_A8F930E24B89032C (post_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seo_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) NOT NULL, meta_description LONGTEXT DEFAULT NULL, focus_keyword VARCHAR(255) DEFAULT NULL, meta_keyword VARCHAR(255) DEFAULT NULL, meta_tags LONGTEXT DEFAULT NULL, state SMALLINT DEFAULT NULL, INDEX IDX_227D72A52C2AC5D3 (translatable_id), INDEX IDX_227D72A582F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seo (id INT AUTO_INCREMENT NOT NULL, seo_base_route_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) NOT NULL, meta_description LONGTEXT DEFAULT NULL, focus_keyword VARCHAR(255) DEFAULT NULL, meta_keyword VARCHAR(255) DEFAULT NULL, meta_tags LONGTEXT DEFAULT NULL, state SMALLINT DEFAULT NULL, last_modified DATETIME NOT NULL, deleted TINYINT(1) DEFAULT \'0\' NOT NULL, INDEX IDX_6C71EC30AB839C52 (seo_base_route_id), UNIQUE INDEX slug_unique (slug, seo_base_route_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE seo_seo_social (seo_id INT NOT NULL, seo_social_id INT NOT NULL, INDEX IDX_F296CD9297E3DD86 (seo_id), INDEX IDX_F296CD922A6ABD62 (seo_social_id), PRIMARY KEY(seo_id, seo_social_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, base_path VARCHAR(255) DEFAULT NULL, size DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, base_path VARCHAR(255) DEFAULT NULL, alt VARCHAR(255) DEFAULT NULL, width DOUBLE PRECISION DEFAULT NULL, height DOUBLE PRECISION DEFAULT NULL, size DOUBLE PRECISION DEFAULT NULL, tarteb SMALLINT DEFAULT NULL, image_type SMALLINT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, post_id INT DEFAULT NULL, seo_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, level_one_id INT DEFAULT NULL, title VARCHAR(100) NOT NULL, concatIds LONGTEXT DEFAULT NULL, tarteb SMALLINT DEFAULT NULL, depth INT NOT NULL, no_of_images SMALLINT DEFAULT 0, no_of_products SMALLINT DEFAULT 0, no_of_publish_products SMALLINT DEFAULT 0, parentConcatIds LONGTEXT DEFAULT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(30) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, UNIQUE INDEX UNIQ_64C19C14B89032C (post_id), UNIQUE INDEX UNIQ_64C19C197E3DD86 (seo_id), INDEX IDX_64C19C1727ACA70 (parent_id), INDEX IDX_64C19C1822CAFB2 (level_one_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_search (product_id INT NOT NULL, currency_id INT DEFAULT NULL, category_id INT DEFAULT NULL, specs LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', normalized_text LONGTEXT DEFAULT NULL, featured TINYINT(1) NOT NULL, recommended_sort SMALLINT NOT NULL, new_arrival TINYINT(1) NOT NULL, has_offer TINYINT(1) NOT NULL, offer_expiry_date DATE DEFAULT NULL, promotion_percentage DOUBLE PRECISION DEFAULT NULL, last_update_datetime DATETIME NOT NULL, INDEX IDX_D68C9A0338248176 (currency_id), FULLTEXT INDEX IDX_D68C9A03B334D8E9 (normalized_text), PRIMARY KEY(product_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_has_attribute (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, attribute_id INT DEFAULT NULL, sub_attribute_id INT DEFAULT NULL, other_value VARCHAR(255) DEFAULT NULL, INDEX IDX_13261464584665A (product_id), INDEX IDX_1326146B6E62EFA (attribute_id), INDEX IDX_1326146A1B469CC (sub_attribute_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE search_keyword (id INT AUTO_INCREMENT NOT NULL, keyword VARCHAR(150) NOT NULL, canonical_keyword VARCHAR(150) NOT NULL, ip VARCHAR(50) NOT NULL, created DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_attribute_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(100) NOT NULL, INDEX IDX_29FE3462C2AC5D3 (translatable_id), INDEX IDX_29FE34682F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(255) NOT NULL, INDEX IDX_4B13F8EC2C2AC5D3 (translatable_id), INDEX IDX_4B13F8EC82F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE category_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(100) NOT NULL, INDEX IDX_1C60F9152C2AC5D3 (translatable_id), INDEX IDX_1C60F91582F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE occasion_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(100) NOT NULL, INDEX IDX_3FAA49AA2C2AC5D3 (translatable_id), INDEX IDX_3FAA49AA82F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_sub_attribute_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(100) NOT NULL, INDEX IDX_FD7FA36F2C2AC5D3 (translatable_id), INDEX IDX_FD7FA36F82F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE collection_translations (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(100) NOT NULL, INDEX IDX_5C94C3AD2C2AC5D3 (translatable_id), INDEX IDX_5C94C3AD82F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_details (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, currency_id INT DEFAULT NULL, tear_sheet_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_A3FF103A4584665A (product_id), INDEX IDX_A3FF103A38248176 (currency_id), UNIQUE INDEX UNIQ_A3FF103AE5F500BE (tear_sheet_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_collection (collection_id INT NOT NULL, product_id INT NOT NULL, created DATETIME NOT NULL, INDEX IDX_6F2A3A19514956FD (collection_id), INDEX IDX_6F2A3A194584665A (product_id), PRIMARY KEY(collection_id, product_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_occasion (occasion_id INT NOT NULL, product_id INT NOT NULL, created DATETIME NOT NULL, INDEX IDX_41D6B6724034998F (occasion_id), INDEX IDX_41D6B6724584665A (product_id), PRIMARY KEY(occasion_id, product_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_sub_attribute (id INT AUTO_INCREMENT NOT NULL, attribute_id INT DEFAULT NULL, title VARCHAR(100) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(30) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, INDEX IDX_329AB5B7B6E62EFA (attribute_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE occasion (id INT AUTO_INCREMENT NOT NULL, seo_id INT DEFAULT NULL, post_id INT DEFAULT NULL, title VARCHAR(45) NOT NULL, start_date DATE DEFAULT NULL, end_date DATE DEFAULT NULL, active TINYINT(1) NOT NULL, publish TINYINT(1) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(30) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, UNIQUE INDEX UNIQ_8A66DCE597E3DD86 (seo_id), UNIQUE INDEX UNIQ_8A66DCE54B89032C (post_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product (id INT AUTO_INCREMENT NOT NULL, seo_id INT DEFAULT NULL, post_id INT DEFAULT NULL, category_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, sku VARCHAR(100) DEFAULT NULL, tarteb SMALLINT DEFAULT NULL, tag VARCHAR(100) DEFAULT NULL, normalized_text LONGTEXT DEFAULT NULL, featured TINYINT(1) NOT NULL, new_arrival TINYINT(1) NOT NULL, publish TINYINT(1) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(30) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, UNIQUE INDEX UNIQ_D34A04AD97E3DD86 (seo_id), UNIQUE INDEX UNIQ_D34A04AD4B89032C (post_id), INDEX IDX_D34A04AD12469DE2 (category_id), FULLTEXT INDEX IDX_D34A04ADB334D8E9 (normalized_text), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prepare_product_search_index (product_id INT NOT NULL, created DATETIME NOT NULL, PRIMARY KEY(product_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_attribute (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, title VARCHAR(100) NOT NULL, type VARCHAR(45) NOT NULL, tarteb SMALLINT DEFAULT NULL, search TINYINT(1) NOT NULL, mandatory TINYINT(1) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(30) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, INDEX IDX_94DA597612469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE collection (id INT AUTO_INCREMENT NOT NULL, seo_id INT DEFAULT NULL, post_id INT DEFAULT NULL, title VARCHAR(45) NOT NULL, publish TINYINT(1) NOT NULL, tarteb SMALLINT DEFAULT 0, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(30) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, UNIQUE INDEX UNIQ_FC4D653297E3DD86 (seo_id), UNIQUE INDEX UNIQ_FC4D65324B89032C (post_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE product_prices (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, min_quantity INT NOT NULL, max_quantity INT NOT NULL, unit_price DOUBLE PRECISION NOT NULL, promotional_price DOUBLE PRECISION DEFAULT NULL, promotional_expiry_date DATE DEFAULT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(30) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, INDEX IDX_86B72CFD4584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE usr (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATETIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:array)\', full_name VARCHAR(255) NOT NULL, phone VARCHAR(15) DEFAULT NULL, facebook_id VARCHAR(255) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(30) DEFAULT NULL, UNIQUE INDEX UNIQ_1762498C92FC23A8 (username_canonical), UNIQUE INDEX UNIQ_1762498CA0D96FBF (email_canonical), UNIQUE INDEX UNIQ_1762498CC05FB297 (confirmation_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE currency (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(50) NOT NULL, code VARCHAR(3) NOT NULL, symbol VARCHAR(255) NOT NULL, deleted DATETIME DEFAULT NULL, deleted_by VARCHAR(30) DEFAULT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, UNIQUE INDEX UNIQ_6956883F77153098 (code), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE currency_translation (translatable_id INT NOT NULL, language_id INT NOT NULL, title VARCHAR(50) NOT NULL, symbol VARCHAR(255) NOT NULL, INDEX IDX_5814BCE2C2AC5D3 (translatable_id), INDEX IDX_5814BCE82F1BAF4 (language_id), PRIMARY KEY(translatable_id, language_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE exchange_rate (id INT AUTO_INCREMENT NOT NULL, source_currency_id INT DEFAULT NULL, target_currency_id INT DEFAULT NULL, ratio DOUBLE PRECISION NOT NULL, created DATETIME NOT NULL, creator VARCHAR(30) NOT NULL, modified DATETIME NOT NULL, modified_by VARCHAR(30) NOT NULL, INDEX IDX_E9521FAB45BD1D6 (source_currency_id), INDEX IDX_E9521FABBF1ECE7C (target_currency_id), UNIQUE INDEX exchange_unique (source_currency_id, target_currency_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE seo_social_translations ADD CONSTRAINT FK_4DC1EE9B2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES seo_social (id)');
        $this->addSql('ALTER TABLE seo_social_translations ADD CONSTRAINT FK_4DC1EE9B82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE seo_page ADD CONSTRAINT FK_E8DCA6F197E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE image_setting_has_type ADD CONSTRAINT FK_F8AEE740505CDB4F FOREIGN KEY (image_type_id) REFERENCES image_type (id)');
        $this->addSql('ALTER TABLE image_setting_has_type ADD CONSTRAINT FK_F8AEE74082EBAA44 FOREIGN KEY (image_setting_id) REFERENCES image_setting (id)');
        $this->addSql('ALTER TABLE dynamic_content_attribute_translations ADD CONSTRAINT FK_A4504A102C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES dynamic_content_attribute (id)');
        $this->addSql('ALTER TABLE dynamic_content_attribute_translations ADD CONSTRAINT FK_A4504A1082F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE dynamic_content_attribute ADD CONSTRAINT FK_E7247B59D9D0CD7 FOREIGN KEY (dynamic_content_id) REFERENCES dynamic_content (id)');
        $this->addSql('ALTER TABLE dynamic_content_attribute_image ADD CONSTRAINT FK_697B9E6EF5E49404 FOREIGN KEY (dynamic_content_attribute_id) REFERENCES dynamic_content_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dynamic_content_attribute_image ADD CONSTRAINT FK_697B9E6E3DA5256D FOREIGN KEY (image_id) REFERENCES image (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dynamic_content_attribute_document ADD CONSTRAINT FK_E9D18348F5E49404 FOREIGN KEY (dynamic_content_attribute_id) REFERENCES dynamic_content_attribute (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dynamic_content_attribute_document ADD CONSTRAINT FK_E9D18348C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_translations ADD CONSTRAINT FK_6D8AA7542C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE post_translations ADD CONSTRAINT FK_6D8AA75482F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE post_image ADD CONSTRAINT FK_522688B04B89032C FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE post_image ADD CONSTRAINT FK_522688B03DA5256D FOREIGN KEY (image_id) REFERENCES image (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE4B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EE97E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE projects_services ADD CONSTRAINT FK_19AF0280166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE projects_services ADD CONSTRAINT FK_19AF0280ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE dynamic_page ADD CONSTRAINT FK_575ACC497E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE dynamic_page ADD CONSTRAINT FK_575ACC44B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61F3DA5256D FOREIGN KEY (image_id) REFERENCES image (id)');
        $this->addSql('ALTER TABLE partner ADD CONSTRAINT FK_312B3E163DA5256D FOREIGN KEY (image_id) REFERENCES image (id)');
        $this->addSql('ALTER TABLE service_translations ADD CONSTRAINT FK_191BAF622C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES service (id)');
        $this->addSql('ALTER TABLE service_translations ADD CONSTRAINT FK_191BAF6282F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE project_translations ADD CONSTRAINT FK_EC103EE42C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES project (id)');
        $this->addSql('ALTER TABLE project_translations ADD CONSTRAINT FK_EC103EE482F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE faq_translations ADD CONSTRAINT FK_99569DA22C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES faq (id)');
        $this->addSql('ALTER TABLE faq_translations ADD CONSTRAINT FK_99569DA282F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE dynamic_page_translations ADD CONSTRAINT FK_5512AA682C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES dynamic_page (id)');
        $this->addSql('ALTER TABLE dynamic_page_translations ADD CONSTRAINT FK_5512AA6882F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE team_translations ADD CONSTRAINT FK_CE31D7452C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES team (id)');
        $this->addSql('ALTER TABLE team_translations ADD CONSTRAINT FK_CE31D74582F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE blogger_translations ADD CONSTRAINT FK_E01D7E42C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES blogger (id)');
        $this->addSql('ALTER TABLE blogger_translations ADD CONSTRAINT FK_E01D7E482F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE partner_translations ADD CONSTRAINT FK_579AC5A62C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES partner (id)');
        $this->addSql('ALTER TABLE partner_translations ADD CONSTRAINT FK_579AC5A682F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE banner_translations ADD CONSTRAINT FK_F8B8D8B2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES banner (id)');
        $this->addSql('ALTER TABLE banner_translations ADD CONSTRAINT FK_F8B8D8B82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE banner ADD CONSTRAINT FK_6F9DB8E73DA5256D FOREIGN KEY (image_id) REFERENCES image (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD24B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD297E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE blogger ADD CONSTRAINT FK_A8F930E297E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE blogger ADD CONSTRAINT FK_A8F930E24B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE seo_translations ADD CONSTRAINT FK_227D72A52C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE seo_translations ADD CONSTRAINT FK_227D72A582F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE seo ADD CONSTRAINT FK_6C71EC30AB839C52 FOREIGN KEY (seo_base_route_id) REFERENCES seo_base_route (id)');
        $this->addSql('ALTER TABLE seo_seo_social ADD CONSTRAINT FK_F296CD9297E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE seo_seo_social ADD CONSTRAINT FK_F296CD922A6ABD62 FOREIGN KEY (seo_social_id) REFERENCES seo_social (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C14B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C197E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1727ACA70 FOREIGN KEY (parent_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1822CAFB2 FOREIGN KEY (level_one_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE product_search ADD CONSTRAINT FK_D68C9A034584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_search ADD CONSTRAINT FK_D68C9A0338248176 FOREIGN KEY (currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE product_has_attribute ADD CONSTRAINT FK_13261464584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_has_attribute ADD CONSTRAINT FK_1326146B6E62EFA FOREIGN KEY (attribute_id) REFERENCES product_attribute (id)');
        $this->addSql('ALTER TABLE product_has_attribute ADD CONSTRAINT FK_1326146A1B469CC FOREIGN KEY (sub_attribute_id) REFERENCES product_sub_attribute (id)');
        $this->addSql('ALTER TABLE product_attribute_translations ADD CONSTRAINT FK_29FE3462C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES product_attribute (id)');
        $this->addSql('ALTER TABLE product_attribute_translations ADD CONSTRAINT FK_29FE34682F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE product_translations ADD CONSTRAINT FK_4B13F8EC2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_translations ADD CONSTRAINT FK_4B13F8EC82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE category_translations ADD CONSTRAINT FK_1C60F9152C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE category_translations ADD CONSTRAINT FK_1C60F91582F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE occasion_translations ADD CONSTRAINT FK_3FAA49AA2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES occasion (id)');
        $this->addSql('ALTER TABLE occasion_translations ADD CONSTRAINT FK_3FAA49AA82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE product_sub_attribute_translations ADD CONSTRAINT FK_FD7FA36F2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES product_sub_attribute (id)');
        $this->addSql('ALTER TABLE product_sub_attribute_translations ADD CONSTRAINT FK_FD7FA36F82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE collection_translations ADD CONSTRAINT FK_5C94C3AD2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES collection (id)');
        $this->addSql('ALTER TABLE collection_translations ADD CONSTRAINT FK_5C94C3AD82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE product_details ADD CONSTRAINT FK_A3FF103A4584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_details ADD CONSTRAINT FK_A3FF103A38248176 FOREIGN KEY (currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE product_details ADD CONSTRAINT FK_A3FF103AE5F500BE FOREIGN KEY (tear_sheet_id) REFERENCES document (id)');
        $this->addSql('ALTER TABLE product_collection ADD CONSTRAINT FK_6F2A3A19514956FD FOREIGN KEY (collection_id) REFERENCES collection (id)');
        $this->addSql('ALTER TABLE product_collection ADD CONSTRAINT FK_6F2A3A194584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_occasion ADD CONSTRAINT FK_41D6B6724034998F FOREIGN KEY (occasion_id) REFERENCES occasion (id)');
        $this->addSql('ALTER TABLE product_occasion ADD CONSTRAINT FK_41D6B6724584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE product_sub_attribute ADD CONSTRAINT FK_329AB5B7B6E62EFA FOREIGN KEY (attribute_id) REFERENCES product_attribute (id)');
        $this->addSql('ALTER TABLE occasion ADD CONSTRAINT FK_8A66DCE597E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE occasion ADD CONSTRAINT FK_8A66DCE54B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD97E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD4B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD12469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE product_attribute ADD CONSTRAINT FK_94DA597612469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE collection ADD CONSTRAINT FK_FC4D653297E3DD86 FOREIGN KEY (seo_id) REFERENCES seo (id)');
        $this->addSql('ALTER TABLE collection ADD CONSTRAINT FK_FC4D65324B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('ALTER TABLE product_prices ADD CONSTRAINT FK_86B72CFD4584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        $this->addSql('ALTER TABLE currency_translation ADD CONSTRAINT FK_5814BCE2C2AC5D3 FOREIGN KEY (translatable_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE currency_translation ADD CONSTRAINT FK_5814BCE82F1BAF4 FOREIGN KEY (language_id) REFERENCES language (id)');
        $this->addSql('ALTER TABLE exchange_rate ADD CONSTRAINT FK_E9521FAB45BD1D6 FOREIGN KEY (source_currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE exchange_rate ADD CONSTRAINT FK_E9521FABBF1ECE7C FOREIGN KEY (target_currency_id) REFERENCES currency (id)');
        $this->addSql('ALTER TABLE team DROP position, DROP short_desc');
        $this->addSql('ALTER TABLE banner ADD actionButton VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE banner_translations ADD actionButton VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE team_translations DROP position, DROP short_desc');
        $this->addSql('ALTER TABLE team ADD position VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE team_translations ADD position VARCHAR(100) NOT NULL');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C14B89032C');
        $this->addSql('DROP INDEX UNIQ_64C19C14B89032C ON category');
        $this->addSql('ALTER TABLE category CHANGE post_id image_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C13DA5256D FOREIGN KEY (image_id) REFERENCES image (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C13DA5256D ON category (image_id)');
        $this->addSql('ALTER TABLE banner ADD tarteb SMALLINT DEFAULT NULL, ADD publish TINYINT(1) NOT NULL');
        $this->addSql('ALTER TABLE product ADD uuid VARCHAR(50) NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D34A04ADD17F50A6 ON product (uuid)');
        $this->addSql('ALTER TABLE product_search ADD min_price DOUBLE PRECISION NOT NULL, ADD max_price DOUBLE PRECISION NOT NULL');
        $this->addSql('ALTER TABLE service_translations ADD contact_text TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE service ADD contact_text TEXT DEFAULT NULL');
        $this->addSql('CREATE TABLE projects_products (project_id INT NOT NULL, product_id INT NOT NULL, INDEX IDX_D927B9B3166D1F9C (project_id), INDEX IDX_D927B9B34584665A (product_id), PRIMARY KEY(project_id, product_id)) DEFAULT CHARACTER SET UTF8 COLLATE `UTF8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE projects_products ADD CONSTRAINT FK_D927B9B3166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE projects_products ADD CONSTRAINT FK_D927B9B34584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema) : void
    {
        $this->addSql('ALTER TABLE banner DROP tarteb, DROP publish');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C13DA5256D');
        $this->addSql('DROP INDEX UNIQ_64C19C13DA5256D ON category');
        $this->addSql('ALTER TABLE category CHANGE image_id post_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C14B89032C FOREIGN KEY (post_id) REFERENCES post (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C14B89032C ON category (post_id)');
        $this->addSql('ALTER TABLE team DROP position');
        $this->addSql('ALTER TABLE team_translations DROP position');
        $this->addSql('ALTER TABLE team_translations ADD position VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, ADD short_desc LONGTEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`');
        $this->addSql('ALTER TABLE banner_translations DROP actionButton');
        $this->addSql('ALTER TABLE banner DROP actionButton');
        $this->addSql('ALTER TABLE team ADD position VARCHAR(50) CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`, ADD short_desc LONGTEXT CHARACTER SET utf8 NOT NULL COLLATE `utf8_unicode_ci`');
        $this->addSql('ALTER TABLE seo DROP FOREIGN KEY FK_6C71EC30AB839C52');
        $this->addSql('ALTER TABLE seo_social_translations DROP FOREIGN KEY FK_4DC1EE9B2C2AC5D3');
        $this->addSql('ALTER TABLE seo_seo_social DROP FOREIGN KEY FK_F296CD922A6ABD62');
        $this->addSql('ALTER TABLE seo_social_translations DROP FOREIGN KEY FK_4DC1EE9B82F1BAF4');
        $this->addSql('ALTER TABLE dynamic_content_attribute_translations DROP FOREIGN KEY FK_A4504A1082F1BAF4');
        $this->addSql('ALTER TABLE post_translations DROP FOREIGN KEY FK_6D8AA75482F1BAF4');
        $this->addSql('ALTER TABLE service_translations DROP FOREIGN KEY FK_191BAF6282F1BAF4');
        $this->addSql('ALTER TABLE project_translations DROP FOREIGN KEY FK_EC103EE482F1BAF4');
        $this->addSql('ALTER TABLE faq_translations DROP FOREIGN KEY FK_99569DA282F1BAF4');
        $this->addSql('ALTER TABLE dynamic_page_translations DROP FOREIGN KEY FK_5512AA6882F1BAF4');
        $this->addSql('ALTER TABLE team_translations DROP FOREIGN KEY FK_CE31D74582F1BAF4');
        $this->addSql('ALTER TABLE blogger_translations DROP FOREIGN KEY FK_E01D7E482F1BAF4');
        $this->addSql('ALTER TABLE partner_translations DROP FOREIGN KEY FK_579AC5A682F1BAF4');
        $this->addSql('ALTER TABLE banner_translations DROP FOREIGN KEY FK_F8B8D8B82F1BAF4');
        $this->addSql('ALTER TABLE seo_translations DROP FOREIGN KEY FK_227D72A582F1BAF4');
        $this->addSql('ALTER TABLE product_attribute_translations DROP FOREIGN KEY FK_29FE34682F1BAF4');
        $this->addSql('ALTER TABLE product_translations DROP FOREIGN KEY FK_4B13F8EC82F1BAF4');
        $this->addSql('ALTER TABLE category_translations DROP FOREIGN KEY FK_1C60F91582F1BAF4');
        $this->addSql('ALTER TABLE occasion_translations DROP FOREIGN KEY FK_3FAA49AA82F1BAF4');
        $this->addSql('ALTER TABLE product_sub_attribute_translations DROP FOREIGN KEY FK_FD7FA36F82F1BAF4');
        $this->addSql('ALTER TABLE collection_translations DROP FOREIGN KEY FK_5C94C3AD82F1BAF4');
        $this->addSql('ALTER TABLE currency_translation DROP FOREIGN KEY FK_5814BCE82F1BAF4');
        $this->addSql('ALTER TABLE image_setting_has_type DROP FOREIGN KEY FK_F8AEE74082EBAA44');
        $this->addSql('ALTER TABLE image_setting_has_type DROP FOREIGN KEY FK_F8AEE740505CDB4F');
        $this->addSql('ALTER TABLE dynamic_content_attribute DROP FOREIGN KEY FK_E7247B59D9D0CD7');
        $this->addSql('ALTER TABLE dynamic_content_attribute_translations DROP FOREIGN KEY FK_A4504A102C2AC5D3');
        $this->addSql('ALTER TABLE dynamic_content_attribute_image DROP FOREIGN KEY FK_697B9E6EF5E49404');
        $this->addSql('ALTER TABLE dynamic_content_attribute_document DROP FOREIGN KEY FK_E9D18348F5E49404');
        $this->addSql('ALTER TABLE post_translations DROP FOREIGN KEY FK_6D8AA7542C2AC5D3');
        $this->addSql('ALTER TABLE post_image DROP FOREIGN KEY FK_522688B04B89032C');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE4B89032C');
        $this->addSql('ALTER TABLE dynamic_page DROP FOREIGN KEY FK_575ACC44B89032C');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD24B89032C');
        $this->addSql('ALTER TABLE blogger DROP FOREIGN KEY FK_A8F930E24B89032C');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C14B89032C');
        $this->addSql('ALTER TABLE occasion DROP FOREIGN KEY FK_8A66DCE54B89032C');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD4B89032C');
        $this->addSql('ALTER TABLE collection DROP FOREIGN KEY FK_FC4D65324B89032C');
        $this->addSql('ALTER TABLE projects_services DROP FOREIGN KEY FK_19AF0280166D1F9C');
        $this->addSql('ALTER TABLE project_translations DROP FOREIGN KEY FK_EC103EE42C2AC5D3');
        $this->addSql('ALTER TABLE dynamic_page_translations DROP FOREIGN KEY FK_5512AA682C2AC5D3');
        $this->addSql('ALTER TABLE team_translations DROP FOREIGN KEY FK_CE31D7452C2AC5D3');
        $this->addSql('ALTER TABLE partner_translations DROP FOREIGN KEY FK_579AC5A62C2AC5D3');
        $this->addSql('ALTER TABLE faq_translations DROP FOREIGN KEY FK_99569DA22C2AC5D3');
        $this->addSql('ALTER TABLE banner_translations DROP FOREIGN KEY FK_F8B8D8B2C2AC5D3');
        $this->addSql('ALTER TABLE projects_services DROP FOREIGN KEY FK_19AF0280ED5CA9E6');
        $this->addSql('ALTER TABLE service_translations DROP FOREIGN KEY FK_191BAF622C2AC5D3');
        $this->addSql('ALTER TABLE blogger_translations DROP FOREIGN KEY FK_E01D7E42C2AC5D3');
        $this->addSql('ALTER TABLE seo_page DROP FOREIGN KEY FK_E8DCA6F197E3DD86');
        $this->addSql('ALTER TABLE project DROP FOREIGN KEY FK_2FB3D0EE97E3DD86');
        $this->addSql('ALTER TABLE dynamic_page DROP FOREIGN KEY FK_575ACC497E3DD86');
        $this->addSql('ALTER TABLE service DROP FOREIGN KEY FK_E19D9AD297E3DD86');
        $this->addSql('ALTER TABLE blogger DROP FOREIGN KEY FK_A8F930E297E3DD86');
        $this->addSql('ALTER TABLE seo_translations DROP FOREIGN KEY FK_227D72A52C2AC5D3');
        $this->addSql('ALTER TABLE seo_seo_social DROP FOREIGN KEY FK_F296CD9297E3DD86');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C197E3DD86');
        $this->addSql('ALTER TABLE occasion DROP FOREIGN KEY FK_8A66DCE597E3DD86');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD97E3DD86');
        $this->addSql('ALTER TABLE collection DROP FOREIGN KEY FK_FC4D653297E3DD86');
        $this->addSql('ALTER TABLE dynamic_content_attribute_document DROP FOREIGN KEY FK_E9D18348C33F7837');
        $this->addSql('ALTER TABLE product_details DROP FOREIGN KEY FK_A3FF103AE5F500BE');
        $this->addSql('ALTER TABLE dynamic_content_attribute_image DROP FOREIGN KEY FK_697B9E6E3DA5256D');
        $this->addSql('ALTER TABLE post_image DROP FOREIGN KEY FK_522688B03DA5256D');
        $this->addSql('ALTER TABLE team DROP FOREIGN KEY FK_C4E0A61F3DA5256D');
        $this->addSql('ALTER TABLE partner DROP FOREIGN KEY FK_312B3E163DA5256D');
        $this->addSql('ALTER TABLE banner DROP FOREIGN KEY FK_6F9DB8E73DA5256D');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1727ACA70');
        $this->addSql('ALTER TABLE category DROP FOREIGN KEY FK_64C19C1822CAFB2');
        $this->addSql('ALTER TABLE category_translations DROP FOREIGN KEY FK_1C60F9152C2AC5D3');
        $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD12469DE2');
        $this->addSql('ALTER TABLE product_attribute DROP FOREIGN KEY FK_94DA597612469DE2');
        $this->addSql('ALTER TABLE product_has_attribute DROP FOREIGN KEY FK_1326146A1B469CC');
        $this->addSql('ALTER TABLE product_sub_attribute_translations DROP FOREIGN KEY FK_FD7FA36F2C2AC5D3');
        $this->addSql('ALTER TABLE occasion_translations DROP FOREIGN KEY FK_3FAA49AA2C2AC5D3');
        $this->addSql('ALTER TABLE product_occasion DROP FOREIGN KEY FK_41D6B6724034998F');
        $this->addSql('ALTER TABLE product_search DROP FOREIGN KEY FK_D68C9A034584665A');
        $this->addSql('ALTER TABLE product_has_attribute DROP FOREIGN KEY FK_13261464584665A');
        $this->addSql('ALTER TABLE product_translations DROP FOREIGN KEY FK_4B13F8EC2C2AC5D3');
        $this->addSql('ALTER TABLE product_details DROP FOREIGN KEY FK_A3FF103A4584665A');
        $this->addSql('ALTER TABLE product_collection DROP FOREIGN KEY FK_6F2A3A194584665A');
        $this->addSql('ALTER TABLE product_occasion DROP FOREIGN KEY FK_41D6B6724584665A');
        $this->addSql('ALTER TABLE product_prices DROP FOREIGN KEY FK_86B72CFD4584665A');
        $this->addSql('ALTER TABLE product_has_attribute DROP FOREIGN KEY FK_1326146B6E62EFA');
        $this->addSql('ALTER TABLE product_attribute_translations DROP FOREIGN KEY FK_29FE3462C2AC5D3');
        $this->addSql('ALTER TABLE product_sub_attribute DROP FOREIGN KEY FK_329AB5B7B6E62EFA');
        $this->addSql('ALTER TABLE collection_translations DROP FOREIGN KEY FK_5C94C3AD2C2AC5D3');
        $this->addSql('ALTER TABLE product_collection DROP FOREIGN KEY FK_6F2A3A19514956FD');
        $this->addSql('ALTER TABLE product_search DROP FOREIGN KEY FK_D68C9A0338248176');
        $this->addSql('ALTER TABLE product_details DROP FOREIGN KEY FK_A3FF103A38248176');
        $this->addSql('ALTER TABLE currency_translation DROP FOREIGN KEY FK_5814BCE2C2AC5D3');
        $this->addSql('ALTER TABLE exchange_rate DROP FOREIGN KEY FK_E9521FAB45BD1D6');
        $this->addSql('ALTER TABLE exchange_rate DROP FOREIGN KEY FK_E9521FABBF1ECE7C');
        $this->addSql('DROP TABLE ext_log_entries');
        $this->addSql('DROP TABLE seo_social_translations');
        $this->addSql('DROP TABLE seo_base_route');
        $this->addSql('DROP TABLE seo_page');
        $this->addSql('DROP TABLE seo_social');
        $this->addSql('DROP TABLE redirect_404');
        $this->addSql('DROP TABLE language');
        $this->addSql('DROP TABLE image_setting');
        $this->addSql('DROP TABLE image_type');
        $this->addSql('DROP TABLE image_setting_has_type');
        $this->addSql('DROP TABLE dynamic_content_attribute_translations');
        $this->addSql('DROP TABLE dynamic_content');
        $this->addSql('DROP TABLE dynamic_content_attribute');
        $this->addSql('DROP TABLE dynamic_content_attribute_image');
        $this->addSql('DROP TABLE dynamic_content_attribute_document');
        $this->addSql('DROP TABLE post_translations');
        $this->addSql('DROP TABLE post');
        $this->addSql('DROP TABLE post_image');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE projects_services');
        $this->addSql('DROP TABLE dynamic_page');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE partner');
        $this->addSql('DROP TABLE faq');
        $this->addSql('DROP TABLE service_translations');
        $this->addSql('DROP TABLE project_translations');
        $this->addSql('DROP TABLE faq_translations');
        $this->addSql('DROP TABLE dynamic_page_translations');
        $this->addSql('DROP TABLE team_translations');
        $this->addSql('DROP TABLE blogger_translations');
        $this->addSql('DROP TABLE partner_translations');
        $this->addSql('DROP TABLE banner_translations');
        $this->addSql('DROP TABLE banner');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE blogger');
        $this->addSql('DROP TABLE seo_translations');
        $this->addSql('DROP TABLE seo');
        $this->addSql('DROP TABLE seo_seo_social');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE image');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE product_search');
        $this->addSql('DROP TABLE product_has_attribute');
        $this->addSql('DROP TABLE search_keyword');
        $this->addSql('DROP TABLE product_attribute_translations');
        $this->addSql('DROP TABLE product_translations');
        $this->addSql('DROP TABLE category_translations');
        $this->addSql('DROP TABLE occasion_translations');
        $this->addSql('DROP TABLE product_sub_attribute_translations');
        $this->addSql('DROP TABLE collection_translations');
        $this->addSql('DROP TABLE product_details');
        $this->addSql('DROP TABLE product_collection');
        $this->addSql('DROP TABLE product_occasion');
        $this->addSql('DROP TABLE product_sub_attribute');
        $this->addSql('DROP TABLE occasion');
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE prepare_product_search_index');
        $this->addSql('DROP TABLE product_attribute');
        $this->addSql('DROP TABLE collection');
        $this->addSql('DROP TABLE product_prices');
        $this->addSql('DROP TABLE usr');
        $this->addSql('DROP TABLE currency');
        $this->addSql('DROP TABLE currency_translation');
        $this->addSql('DROP TABLE exchange_rate');
        $this->addSql('DROP TABLE projects_products');
        $this->addSql('ALTER TABLE service DROP contact_text');
        $this->addSql('ALTER TABLE service_translations DROP contact_text');
        $this->addSql('ALTER TABLE product_search DROP min_price, DROP max_price');
        $this->addSql('DROP INDEX UNIQ_D34A04ADD17F50A6 ON product');
        $this->addSql('ALTER TABLE product DROP uuid');
    }
}
