<?php

namespace PN\Bundle\CMSBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use PN\Bundle\CMSBundle\Entity\Service;
use PN\ServiceBundle\Utils\SQL;
use PN\ServiceBundle\Utils\Validate;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function find($id, $lockMode = null, $lockVersion = null)
    {
        $statement = $this->getStatement();
        $statement->where("s.id=:id");
        $statement->setParameter("id", $id);
        return $statement->getQuery()->getOneOrNullResult();
    }

    public function findAll()
    {
        $statement = $this->getStatement();
        $statement->where("s.deleted IS NULL");
        return $statement->getQuery()->execute();
    }

    private function getStatement()
    {
        return $this->createQueryBuilder('s');
    }

    private function filterOrder(QueryBuilder $statement, \stdClass $search)
    {
        $sortSQL = [
            's.id',
            's.tarteb',
            's.title',
            's.publish',
            's.created'
        ];

        if (isset($search->ordr) and Validate::not_null($search->ordr)) {
            $dir = $search->ordr['dir'];
            $columnNumber = $search->ordr['column'];
            if (isset($columnNumber) and array_key_exists($columnNumber, $sortSQL)) {
                $statement->addOrderBy($sortSQL[$columnNumber], $dir);
            }
        } else {
            $statement->addOrderBy($sortSQL[1]);
        }
    }

    private function filterWhereClause(QueryBuilder $statement, \stdClass $search)
    {
        if (isset($search->string) and Validate::not_null($search->string)) {
            $statement->andWhere('s.id LIKE :searchTerm '
                . 'OR s.title LIKE :searchTerm '
            );
            $statement->setParameter('searchTerm', '%' . trim($search->string) . '%');
        }

        if (isset($search->publish) and $search->publish != "") {
            $statement->andWhere('s.publish = :publish');
            $statement->setParameter('publish', $search->publish);
        }

        if (isset($search->notId) and $search->notId != "") {
            $statement->andWhere('s.id <> :notId');
            $statement->setParameter('notId', $search->notId);
        }


        if (isset($search->deleted) and in_array($search->deleted, array(0, 1))) {
            if ($search->deleted == 1) {
                $statement->andWhere('s.deleted IS NOT NULL');
            } else {
                $statement->andWhere('s.deleted IS NULL');
            }
        }
    }

    private function filterPagination(QueryBuilder $statement, $startLimit = NULL, $endLimit = NULL)
    {
        if ($startLimit === NULL or $endLimit === NULL) {
            return false;
        }
        $statement->setFirstResult($startLimit)
            ->setMaxResults($endLimit);
    }

    private function filterCount(QueryBuilder $statement)
    {
        $statement->select("COUNT(DISTINCT s.id)");
        $statement->setMaxResults(1);

        $count = $statement->getQuery()->getOneOrNullResult();
        if (is_array($count) and count($count) > 0) {
            return (int)reset($count);
        }
        return 0;
    }

    public function filter($search, $count = FALSE, $startLimit = NULL, $endLimit = NULL)
    {
        $statement = $this->getStatement();
        $this->filterWhereClause($statement, $search);

        if ($count == true) {
            return $this->filterCount($statement);
        }

        $statement->groupBy('s.id');
        $this->filterPagination($statement, $startLimit, $endLimit);
        $this->filterOrder($statement, $search);
        return $statement->getQuery()->execute();
    }

    public function getProjectsIdsUsingService(Service $service)
    {
        $em = $this->getEntityManager();
        $serviceId = $service->getId();

        $sql = "SELECT project_id
                FROM projects_services
                WHERE service_id = $serviceId";

        $statement = $em->getConnection()->prepare($sql);
        $statement->execute();
        $results = $statement->fetchAll();

        $ids = [];
        if (!empty($results)) {
            foreach ($results as $result) {
                $ids[] = $result["project_id"];
            }
        }

        return $ids;
    }

}
