<?php

namespace PN\Bundle\CMSBundle\Repository;

use PN\ServiceBundle\Utils\SQL;
use PN\ServiceBundle\Utils\Validate;

/**
 * MangmentTeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository {

    public function filter($search, $count = FALSE, $startLimit = NULL, $endLimit = NULL) {

        $sortSQL = [
            't.tarteb',
            't.name',
            't.position',
            't.publish',
        ];

        $connection = $this->getEntityManager()->getConnection();
        $where = FALSE;
        $clause = '';

        $searchFiltered = new \stdClass();
        foreach ($search as $key => $value) {
            if (Validate::not_null($value) AND ! is_array($value)) {
                $searchFiltered->{$key} = substr($connection->quote($value), 1, -1);
            } else {
                $searchFiltered->{$key} = $value;
            }
        }

        if (isset($searchFiltered->publish) AND in_array($searchFiltered->publish, array(0, 1))) {
            $where = ($where) ? " AND " : " WHERE ";
            $clause .= $where . " t.publish = $searchFiltered->publish ";
        }

        if (isset($searchFiltered->deleted) AND in_array($searchFiltered->deleted, array(0, 1))) {
            $where = ($where) ? " AND " : " WHERE ";
            if ($searchFiltered->deleted == 1) {
                $clause .= $where . " t.deleted IS NOT NULL ";
            } else {
                $clause .= $where . " t.deleted IS NULL ";
            }
        }

        if (isset($searchFiltered->string) AND $searchFiltered->string) {

            if (SQL::validateSS($searchFiltered->string)) {
                $where = ($where) ? ' AND ( ' : ' WHERE ( ';
                $clause .= SQL::searchSCG($searchFiltered->string, 't.id', $where);
                $clause .= SQL::searchSCG($searchFiltered->string, 't.name', ' OR ');
                $clause .= SQL::searchSCG($searchFiltered->string, 't.position', ' OR ');
                $clause .= SQL::searchSCG($searchFiltered->string, 't.companyName', ' OR ');
                $clause .= " ) ";
            }
        }



        if ($count) {
            $sqlInner = 'SELECT COUNT(t.id) AS `count` FROM team t ';
            $sqlInner .= $clause;

            $statement = $connection->prepare($sqlInner);
            $statement->execute();
            return $queryResult = $statement->fetchColumn();
        }
//----------------------------------------------------------------------------------------------------------------------------------------------------
        $sql = 'SELECT t.id FROM team t ';
        $sql .= $clause;
        if (isset($searchFiltered->ordr) AND Validate::not_null($searchFiltered->ordr)) {
            $dir = $searchFiltered->ordr['dir'];
            $columnNumber = $searchFiltered->ordr['column'];
            if (isset($columnNumber) AND array_key_exists($columnNumber, $sortSQL)) {
                $sql .= " ORDER by " . $sortSQL[$columnNumber] . " $dir";
            }
        } else {
            $sql .= ' ORDER by t.id DESC';
        }

        if ($startLimit !== NULL AND $endLimit !== NULL) {
            $sql .= " LIMIT " . $startLimit . ", " . $endLimit;
        }
        $statement = $connection->prepare($sql);
        $statement->execute();
        $filterResult = $statement->fetchAll();
        $result = array();

        foreach ($filterResult as $key => $r) {
            $result[] = $this->find($r['id']);
        }
//-----------------------------------------------------------------------------------------------------------------------
        return $result;
    }

}
